version: '3.7'

services:
  myapp:
    image: jaroslawksiezuk/laravel
    ports:
      - '8000:8000'
    volumes:
      - './app/Http/Controllers/Frontend:/laravel/app/Http/Controllers/Frontend'
      - './app/Models:/laravel/app/Models'
      - './public/assets:/laravel/public/assets'
      - './resources/views:/laravel/resources/views'
      - type: bind
        source: ./routes/web.php
        target: /laravel/routes/web.php
